CREATE TABLE IF NOT EXISTS cards (
  card_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mobile_number VARCHAR(20),
  card_number VARCHAR(100),
  card_type VARCHAR(100),
  total_limit INT NOT NULL,
  amount_used INT NOT NULL,
  available_amount INT NOT NULL,
  created_at DATE NOT NULL,
  created_by VARCHAR(20),
  updated_at DATE DEFAULT NULL,
  updated_by VARCHAR(20) DEFAULT NULL
);