CREATE TABLE IF NOT EXISTS loans (
  loan_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mobile_number VARCHAR(15),
  loan_number VARCHAR(100),
  loan_type VARCHAR(100),
  total_loan INT NOT NULL,
  amount_paid INT NOT NULL,
  outstanding_amount INT NOT NULL,
  created_at DATE NOT NULL,
  created_by VARCHAR(20),
  updated_at DATE DEFAULT NULL,
  updated_by VARCHAR(20) DEFAULT NULL
);